### PR TITLE
Update eosio.rb

### PR DESCRIPTION
**Pull request by georgipopivanov**
Added dependencies and the universal option which ultimately resolves [issue 50](https://github.com/EOSIO/homebrew-eosio/issues/50)

### CODE REVIEW

**Comment by killshot13** [comment]
Thank you @georgipopivanov. I was aware of the additional disparities, but being a new contributor, I wasn't sure if it was my place to make all those changes at one time. I appreciate the help in getting this squared away.

**Comment by spoonincode** [comment]
I don't think this is the right location to make changes. I believe the file is auto populated from
https://github.com/EOSIO/eos/blob/master/scripts/generate_bottle.sh

**Comment by spoonincode** [comment]
ah Zach already mentioned something similar in https://github.com/EOSIO/homebrew-eosio/issues/50#issuecomment-859658922

**Review by kj4ezj — CHANGES_REQUESTED** [review]
Thank you so much for contributing, this is helpful! I just found one mistake below.

As @spoonincode mentioned, this will only fix the issue until the next release because the CI system will automatically overwrite this ruby file using packaging scripts in EOSIO [here](https://github.com/EOSIO/eos/blob/2b734ff0e25197301e2435b28c17ea51aa711d57/scripts/generate_bottle.sh). We still want to merge this to suppress the `brew` warnings for the current release, but the same changes will have to be made there on `eos:develop`, `eos:release/2.1.x`, and `eos:release/2.0.x` to persist. That would be a worthwhile contribution for anyone interested.

**Comment by kj4ezj** [comment]
Internal tracking: [EPE944](https://blockone.atlassian.net/browse/EPE-944) and [EPE-1044](https://blockone.atlassian.net/browse/EPE-1044) (duplicates)

**Comment by praphael** [comment]
> I don't think this is the right location to make changes. I believe the file is auto populated from
> https://github.com/EOSIO/eos/blob/master/scripts/generate_bottle.sh

I have created a PR for this  
https://github.com/EOSIO/eos/pull/10428

**Comment by kj4ezj** [comment]
We prefer to give community contributors more time to address peer-review feedback, but this warning is impacting all EOSIO users installing via homebrew and it has been a week so I just went ahead and made the bug fix so we can get it merged.

Thank you to @gleehokie and @wly99 for reporting this issue, and to @georgipopivanov and @killshot13 for putting up fixes. We really appreciate it, that was the hard part.

**Pull request merged**
